# -*- coding: utf-8 -*-
"""src-code2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbCgqkB5R-CCaCYwPCfa0fAZOI6th728
"""

import pandas as pd

clean_data = pd.read_csv("StudentsPerformance.csv")

import matplotlib.pyplot as plt

race_count = clean_data['race/ethnicity'].value_counts()
plt.bar(race_count.index, race_count.values)
plt.title('Ethnicity count')
plt.xlabel('Race')
plt.ylabel('Count')
plt.show()

import seaborn as sns

sns.boxplot(x = 'lunch', y = 'math score', data=clean_data)
plt.title('lunch vs score')
plt.show()



plt.scatter(clean_data['test preparation course'], clean_data['reading score'], )
plt.title('test preparation course vs reading score')
plt.xlabel('test preparation course')
plt.ylabel('Reading score')
plt.show()

plt.scatter(clean_data['parental level of education'], clean_data['writing score'], )
plt.title('parental level of education vs writing score')
plt.xlabel('parental level of education')
plt.ylabel('writing score')
plt.show()



sns.kdeplot(x='reading score', data=clean_data, hue = 'race/ethnicity', fill=True, alpha=.4)
plt.title('Reading scores by race/ethnicity')
plt.xlabel('Reading score')
plt.show()